#!/usr/bin/env node
/**
 * Synchronises a release version across the monorepo. Invoked by
 * `@semantic-release/exec` during the `prepare` step:
 *
 *   node scripts/set-version.mjs 1.4.0
 *
 * It rewrites:
 *   - the `version` field of the root package.json and every published workspace
 *   - packages/sdk/src/version.ts (the auto-generated `VERSION` constant)
 *
 * Manual version bumps are no longer needed — semantic-release derives the
 * version from Conventional Commits and calls this script.
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const version = process.argv[2]
if (!version || !/^\d+\.\d+\.\d+(?:-[\w.]+)?$/.test(version)) {
  console.error(`set-version: invalid or missing version argument: "${version ?? ''}"`)
  process.exit(1)
}

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')

const packageJsonFiles = [
  'package.json',
  'packages/sdk/package.json',
  'packages/react/package.json',
  'packages/mock-rpc/package.json',
]

for (const rel of packageJsonFiles) {
  const path = resolve(root, rel)
  try {
    const pkg = JSON.parse(readFileSync(path, 'utf8'))
    pkg.version = version
    writeFileSync(path, JSON.stringify(pkg, null, 2) + '\n')
    console.log(`set-version: ${rel} -> ${version}`)
  } catch (err) {
    console.warn(`set-version: skipped ${rel} (${err.message})`)
  }
}

const versionTsPath = resolve(root, 'packages/sdk/src/version.ts')
writeFileSync(
  versionTsPath,
  `// This file is auto-generated by scripts/set-version.mjs during semantic-release.\n` +
    `// Do not edit by hand — version bumps are driven by Conventional Commits.\n` +
    `export const VERSION = '${version}'\n`,
)
console.log(`set-version: packages/sdk/src/version.ts -> ${version}`)
